---

- set_fact:
    zabbix_agent_version: "2.2.23-1+wheezy_{{ system_architecture|default('amd64') }}"

- name: "Remove deprecated zabbix repo"
  apt_repository: repo={{ item }} state=absent
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/2.2/debian/ {{ ansible_distribution_release }} main'
    - 'deb http://repo.zabbix.com/zabbix/2.4/debian/ {{ ansible_distribution_release }} main'

- stat: path=/etc/zabbix/zabbix_agentd.conf.ucf-dist
  register: ucf_dist

- name: "Move zabbix_agentd.conf.ucf-dist -> zabbix_agentd.conf"
  command: mv /etc/zabbix/zabbix_agentd.conf.ucf-dist /etc/zabbix/zabbix_agentd.conf
  when: ucf_dist.stat.exists

# Using apt with a deb downloads the deb everytime we call ansible
#- apt: deb=https://download.elastic.co/logstash/logstash/packages/debian/logstash_2.1.1-1_all.deb

- name: Downloading zabbix-agent.deb
  # Providing the name of the destination file will skip the download if the file exists
  get_url: url=http://repo.zabbix.com/zabbix/2.2/debian/pool/main/z/zabbix/zabbix-agent_{{ zabbix_agent_version }}.deb dest=/var/cache/apt/archives/zabbix-agent_{{ zabbix_agent_version }}.deb

- name: Downloading zabbix-sender.deb
  # Providing the name of the destination file will skip the download if the file exists
  get_url: url=http://repo.zabbix.com/zabbix/2.2/debian/pool/main/z/zabbix/zabbix-sender_{{ zabbix_agent_version }}.deb dest=/var/cache/apt/archives/zabbix-sender_{{ zabbix_agent_version }}.deb

# We use force as we have previously installed 2.4.8 and we now do a downgrade
- name: "Installing zabbix-agent.deb"
  apt: force=yes deb=/var/cache/apt/archives/zabbix-agent_{{ zabbix_agent_version }}.deb
- name: "Installing zabbix-sender.deb"
  apt: deb=/var/cache/apt/archives/zabbix-sender_{{ zabbix_agent_version }}.deb

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: "Configure zabbix-agent ({{ zabbix_agent_conf }})"
  template: src={{ zabbix_agent_conf }}
            dest=/etc/zabbix/zabbix_agentd.d/{{ zabbix_agent_conf }}
            mode=0644
  notify: "Restart zabbix-agent"

#- name: "Ensure local-userparameter-os-updates.conf"
#  copy: src=local-userparameter-os-updates.conf dest=/etc/zabbix/fix-me-in-Linux-Debian_7.yml
#  notify: "Restart zabbix-agent"

- name: Start the zabbix-agent service
  service: name=zabbix-agent state=started enabled=yes

