---

# Contains the path to the dir without final '/' (was mixed before 2021-11-12)
- set_fact:
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.conf.d

- name: Install zabbix-agent (package from OS / Debian)
  include_tasks: zabbix-agent-from-os.yml
  when: zabbix_agent_version is not defined

- name: Install zabbix-agent (package from zabbix.org)
  include_tasks: zabbix-agent-from-zabbix.org.yml
  when: zabbix_agent_version is defined

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: Configure zabbix-agent ({{ zabbix_agent_conf }})
  template:
    src: "{{ zabbix_agent_conf }}"
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: 0644
  notify: "Restart zabbix-agent"

- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (1/2)
  shell: openssl rand -hex 32 > {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk
  args:
    creates: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
  notify: Restart zabbix-agent

- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (2/2)
  file:
    path: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
    owner: root
    group: zabbix
    mode: 0640

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Copy logcheck rules
  copy:
    src: logcheck-zabbix-agent
    dest: /etc/logcheck/ignore.d.server/mit-defaults-zabbix-agent
  when: "'logcheck' in ansible_facts.packages"

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service:
    name: zabbix-agent.service
    state: started
    enabled: yes

