---

- name: Install zabbix-agent (package from OS / Debian)
  include_tasks: zabbix-agent-from-os.yml
  when: zabbix_agent_version is not defined

- name: Install zabbix-agent (package from zabbix.org)
  include_tasks: zabbix-agent-from-zabbix.org.yml
  when: zabbix_agent_version is defined

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: "Configure zabbix-agent ({{ zabbix_agent_conf }})"
  template: src={{ zabbix_agent_conf }}
            dest=/etc/zabbix/zabbix_agentd.conf.d/{{ zabbix_agent_conf }}
            mode=0644
  notify: "Restart zabbix-agent"

- name: Copy local-userparameter_system-sw-packages-version.conf
  copy: 
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.conf.d/
  loop:
    - local-userparameter_local-web-page-get.conf
    - local-userparameter_systemd-timesyncd-timedatectl.conf
    - local-userparameter_system-sw-packages-version.conf
  notify: "Restart zabbix-agent"

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service: name=zabbix-agent.service state=started enabled=yes

