---

- set_fact:
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.conf.d/

- name: Install zabbix-agent (package from OS / Debian)
  include_tasks: zabbix-agent-from-os.yml
  when: zabbix_agent_version is not defined

- name: Install zabbix-agent (package from zabbix.org)
  include_tasks: zabbix-agent-from-zabbix.org.yml
  when: zabbix_agent_version is defined

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: "Configure zabbix-agent ({{ zabbix_agent_conf }})"
  template: src={{ zabbix_agent_conf }}
            dest=/etc/zabbix/zabbix_agentd.conf.d/{{ zabbix_agent_conf }}
            mode=0644
  notify: "Restart zabbix-agent"

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service: name=zabbix-agent.service state=started enabled=yes

