---
# We use instead of 3.0.7+dfsg-3 (Debian 9) as we want to use logrt.count (#19739)
# 4.0.4+dfsg-1 is not for Debian 9, don't use it!
- ansible.builtin.set_fact:
    zabbix_agent_version: 4.0.3+dfsg-2~bpo9+1_{{ system_architecture | default('amd64') }}
# Contains the path to the dir without final '/' (was mixed before 2021-11-12)
- ansible.builtin.set_fact:
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.conf.d

# Using apt with a deb downloads the deb everytime we call ansible
#- apt: deb=https://download.elastic.co/logstash/logstash/packages/debian/logstash_2.1.1-1_all.deb

- name: Downloading deb
  # Providing the name of the destination file will skip the download if the file exists
  ansible.builtin.get_url:
    url: http://ftp.de.debian.org/debian/pool/main/z/zabbix/zabbix-agent_{{
    dest: /var/cache/apt/archives/zabbix-agent_{{
    cmd: zabbix_agent_version }}.deb zabbix_agent_version }}.deb
- name: Installing deb
  ansible.builtin.apt:
    deb: /var/cache/apt/archives/zabbix-agent_{{
    cmd: zabbix_agent_version }}.deb
- name: Add user zabbix to group adm
  ansible.builtin.user:
    name: zabbix
    append: true
    groups: adm
  notify: Restart zabbix-agent

- name: Configure zabbix-agent ({{ zabbix_agent_conf }})
  ansible.builtin.template:
    src: "{{ zabbix_agent_conf }}"
    # We use the same name for all which makes it easier if we change the
    # template for some hosts (myconf1.conf -> myconf2.conf)
    dest: "{{ zabbix_agent_conf_dir }}/local-zabbix_agentd.conf"
    mode: "0644"
  notify: Restart zabbix-agent

- name: Remove deprecated {{ zabbix_agent_conf_dir }}/{{ zabbix_agent_conf }}
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf_dir }}/{{ zabbix_agent_conf }}"
    state: absent
  notify: Restart zabbix-agent

- name: Copy {{ item }}
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.conf.d/
  with_items:
    - local-userparameter_systemd-timesyncd-timedatectl.conf
  notify: Restart zabbix-agent

- name: Start the zabbix-agent service
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: "yes"
