---

- set_fact:
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.conf.d/

- name: "Ensure zabbix-agent is installed"
  apt: pkg=zabbix-agent
       state=present
       update_cache=yes
       cache_valid_time=3600

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: Configure zabbix-agent ({{ zabbix_agent_conf }})
  template:
    src: "{{ zabbix_agent_conf }}"
    # We use the same name for all which makes it easier if we change the
    # template for some hosts (myconf1.conf -> myconf2.conf)
    dest: "{{ zabbix_agent_conf_dir }}/local-zabbix_agentd.conf"
    mode: 0644
  notify: "Restart zabbix-agent"

- name: Remove deprecated {{ zabbix_agent_conf_dir }}/{{ zabbix_agent_conf }}
  file:
    path: "{{ zabbix_agent_conf_dir }}/{{ zabbix_agent_conf }}"
    state: absent
  notify: "Restart zabbix-agent"

- name: Copy local-userparameter_system-sw-packages-version.conf
  copy: 
    src: "{{ item }}"
    dest: /etc/zabbix/zabbix_agentd.conf.d/
  loop:
    - local-userparameter_local-web-page-get.conf
    - local-userparameter_systemd-timesyncd-timedatectl.conf
    - local-userparameter_system-sw-packages-version.conf
  notify: "Restart zabbix-agent"

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service: name=zabbix-agent.service state=started enabled=yes

