---

- set_fact:
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.conf.d/

- name: "Ensure zabbix-agent is installed"
  apt: pkg=zabbix-agent
       state=present
       update_cache=yes
       cache_valid_time=3600

#17539: Zur Aktualisierung verfügbare Pakete mit Zabbix prüfen
#- name: "Installing dependencies"
#  apt: name=update-notifier-common state=present

- name: "Configure zabbix-agent"
  template: src=local-mit-zabbix_agent.conf
            dest=/etc/zabbix/zabbix_agentd.conf.d/local-mit-zabbix_agent.conf
            mode=0644
  notify: "Restart zabbix-agent"

#- name: "Ensure local-userparameter-os-updates.conf"
#  copy: src=local-userparameter-os-updates.conf dest=/etc/zabbix/fix-me-in-Linux-Debian_8.yml
#  notify: "Restart zabbix-agent"

- name: Start the zabbix-agent service
  service: name=zabbix-agent state=started enabled=yes

