---

# Setup used for Synology

- set_fact:
    zabbix_agent_version: "4.0.30"
- set_fact:
    zabbix_agent_tgz: "zabbix_agent-{{ zabbix_agent_version }}-linux-3.0-{{ system_architecture|default('amd64') }}-static.tar.gz"
- set_fact:
    zabbix_agent_conf_dir: /volume1/zabbix/conf/zabbix_agentd/

# This doesn't work on every machine, simply use:
# curl https://cdn.zabbix.com/zabbix/binaries/stable/4.0/4.0.30/zabbix_agent-4.0.30-linux-3.0-amd64-static.tar.gz
- name: "Downloading pre-compiled Linux agent"
  # Providing the name of the destination file will skip the download if the file exists
  get_url: url=https://cdn.zabbix.com/zabbix/binaries/stable/4.0/{{ zabbix_agent_version }}/{{ zabbix_agent_tgz }} dest=/tmp/{{ zabbix_agent_tgz }}

- file: path=/volume1/zabbix state=directory

- name: "Extracting agent"
  unarchive: 
    src: /tmp/{{ zabbix_agent_tgz }}
    dest: /volume1/zabbix
    remote_src: true

- name: "Installing zabbix as service"
  copy: src=init-zabbix-agent.conf dest=/etc/init/zabbix-agent.conf

# Zabbix runs with user nobody currently as useradd is not available
#- name: "Ensure user zabbix"
#  user: name=zabbix system=true

- name: "Ensure include in zabbix configuration"
  lineinfile:
    dest: /volume1/zabbix/conf/zabbix_agentd.conf
    regexp: "^# Include="
    line: "Include=/volume1/zabbix/conf/zabbix_agentd/*.conf"
    insertafter: true

- name: Disable conf/zabbix_agentd/userparameter_examples.conf
  command: mv /volume1/zabbix/conf/zabbix_agentd/userparameter_examples.conf /volume1/zabbix/conf/zabbix_agentd/userparameter_examples.conf.disabled

- name: "Configure zabbix-agent"
  template: src={{ zabbix_agent_conf }}
            dest=/volume1/zabbix/conf/zabbix_agentd/local-mit-zabbix_agent.conf
            mode=0644
  notify: "Restart zabbix-agent"

# Synology DSM uses upstart:
# sudo start zabbix-agent
# sudo tail -F /var/log/upstart/zabbix-agent.log
- name: Start the zabbix-agent service
  service: name=zabbix-agent state=started enabled=yes

