---

- name: "Remove deprecated zabbix repo"
  apt_repository: repo={{ item }} state=absent
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/2.2/debian/ {{ ansible_distribution_release }} main'
    - 'deb http://repo.zabbix.com/zabbix/2.4/debian/ {{ ansible_distribution_release }} main'
    - 'deb http://repo.zabbix.com/zabbix/2.2/debian/ wheezy main'
    - 'deb http://repo.zabbix.com/zabbix/2.4/debian/ wheezy main'

- name: "Ensure zabbix-agent v2.4 is not installed"
  apt: pkg={{ item }} state=absent
  with_items:
    - zabbix-agent=1:2.2.18-1+jessie
    - zabbix-agent=1:2.2.18-1+wheezy
    - zabbix-agent=1:2.2.21-1+wheezy
    - zabbix-agent=1:2.4.8-1+jessie
    - zabbix-agent=1:2.4.8-1+wheezy
    - zabbix-sender=1:2.2.21-1+wheezy
    - zabbix-sender=1:2.4.8-1+wheezy

- name: "Ensure zabbix.com include dir is absent"
  file: path=/etc/zabbix/zabbix_agentd.d state=absent

- name: "Ensure zabbix-agent is installed"
  apt: pkg=zabbix-agent
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Copy local-userparameter_system-sw-packages-version.conf
  copy: src=local-userparameter_system-sw-packages-version.conf
        dest=/etc/zabbix/zabbix_agentd.conf.d/
  notify: "Restart zabbix-agent"

- name: Copy local-userparameter_systemd-timesyncd-timedatectl.conf
  copy: src=local-userparameter_systemd-timesyncd-timedatectl.conf
        dest=/etc/zabbix/zabbix_agentd.conf.d/
  notify: "Restart zabbix-agent"

- name: "Configure zabbix-agent ({{ zabbix_agent_conf }})"
  template: src={{ zabbix_agent_conf }}
            dest=/etc/zabbix/zabbix_agentd.conf.d/{{ zabbix_agent_conf }}
            mode=0644
  notify: "Restart zabbix-agent"

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service: name=zabbix-agent.service state=started enabled=yes

