---

- set_fact:
    # Contains the path to the dir without final '/' (was mixed before 2021-11-12)
    zabbix_agent_conf_dir: /etc/zabbix/zabbix_agentd.d
    zabbix_major_version: "{{ zabbix_agent_version | regex_replace('^([0-9]+\\.[0-9]+)(.*)$', '\\1') }}"

- set_fact:
    # https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent-6.0.9-release1.el8.x86_64.rpm
    zabbix_repo_base: "https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/"
    zabbix_agent_package:   "zabbix-agent-{{ zabbix_agent_version }}-release1.el{{ ansible_distribution_major_version }}.x86_64.rpm"
    zabbix_sender_package: "zabbix-sender-{{ zabbix_agent_version }}-release1.el{{ ansible_distribution_major_version }}.x86_64.rpm"

#- name: Remove depreated gpg keys
#  ansible.builtin.rpm_key:
#    state: absent
#    key: "{{ item }}"
#  with_items:
#    - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
#    - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD
#    - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-79EA5ED4
#  environment: "{{ proxy_env }}"

- name: Import zabbix gpg key for rpm
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
  environment: "{{ proxy_env }}"

- name: Installing zabbix-agent v{{ zabbix_agent_version }}
  ansible.builtin.dnf:
    name: "{{ zabbix_repo_base }}{{ zabbix_sender_package }}"
    state: present
  environment: "{{ proxy_env }}"

- name: Installing zabbix-sender v{{ zabbix_agent_version }}
  ansible.builtin.dnf:
    name: "{{ zabbix_repo_base }}{{ zabbix_agent_package }}"
    state: present
  environment: "{{ proxy_env }}"

- name: Configure zabbix-agent ({{ zabbix_agent_conf }})
  template:
    src: "{{ zabbix_agent_conf }}"
    # We use the same name for all which makes it easier if we change the
    # template for some hosts (myconf1.conf -> myconf2.conf)
    dest: "{{ zabbix_agent_conf_dir }}/local-zabbix_agentd.conf"
    mode: 0644
  notify: "Restart zabbix-agent"

- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (1/2)
  shell: openssl rand -hex 32 > {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk
  args:
    creates: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
  notify: Restart zabbix-agent

- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (2/2)
  file:
    path: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
    owner: root
    group: zabbix
    mode: 0640

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service:
    name: zabbix-agent.service
    state: started
    enabled: yes

