---
# Setup used for Synology

- ansible.builtin.set_fact:
    zabbix_agent_version: 4.0.30
- ansible.builtin.set_fact:
    zabbix_agent_tgz: zabbix_agent-{{ zabbix_agent_version }}-linux-3.0-{{ system_architecture | default('amd64') }}-static.tar.gz
- ansible.builtin.set_fact:
    zabbix_agent_conf_dir: /volume1/zabbix/conf/zabbix_agentd/

# This doesn't work on every machine, simply use:
# curl https://cdn.zabbix.com/zabbix/binaries/stable/4.0/4.0.30/zabbix_agent-4.0.30-linux-3.0-amd64-static.tar.gz
- name: Downloading pre-compiled Linux agent
  # Providing the name of the destination file will skip the download if the file exists
  ansible.builtin.get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/4.0/{{
    dest: /tmp/{{
    cmd: zabbix_agent_version }}/{{ zabbix_agent_tgz }} zabbix_agent_tgz }}
- ansible.builtin.file:
    path: /volume1/zabbix
    state: directory
- name: Extracting agent
  ansible.builtin.unarchive:
    src: /tmp/{{ zabbix_agent_tgz }}
    dest: /volume1/zabbix
    remote_src: true

- name: Installing zabbix as service
  ansible.builtin.copy:
    src: init-zabbix-agent.conf
    dest: /etc/init/zabbix-agent.conf
- name: Ensure include in zabbix configuration
  ansible.builtin.lineinfile:
    dest: /volume1/zabbix/conf/zabbix_agentd.conf
    regexp: ^# Include=
    line: Include=/volume1/zabbix/conf/zabbix_agentd/*.conf
    insertafter: true

- name: Disable conf/zabbix_agentd/userparameter_examples.conf
  ansible.builtin.command: mv /volume1/zabbix/conf/zabbix_agentd/userparameter_examples.conf /volume1/zabbix/conf/zabbix_agentd/userparameter_examples.conf.disabled
- name: Configure zabbix-agent
  ansible.builtin.template:
    src: "{{"
    dest: /volume1/zabbix/conf/zabbix_agentd/local-mit-zabbix_agent.conf
    mode: "0644"
    cmd: zabbix_agent_conf }}
  notify: Restart zabbix-agent

# Synology DSM uses upstart:
# sudo start zabbix-agent
# sudo tail -F /var/log/upstart/zabbix-agent.log
- name: Start the zabbix-agent service
  ansible.builtin.service:
    name: zabbix-agent
    state: started
    enabled: "yes"
