---
# We use ansible_lsb.id instead of ansible_distribution as this adds support for
# UCS (Univention Corporate Server) which reports ansible_distribution=Debian and
# ansible_lsb.id=Univention

- name: Include ansible_system-ansible_lsb.id_ansible_lsb.major_release.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: ansible_lsb is defined and ansible_lsb.id is defined and tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_lsb.id | default('') }}_{{ ansible_lsb.major_release | default('') }}.yml" # Linux-Debian_12.yml

- name: Include ansible_system-ansible_distribution_ansible_distribution_major_version-ansible_machine.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: (ansible_lsb is not defined or ansible_lsb.id is not defined) and ansible_distribution_major_version is defined and tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_distribution }}_{{ ansible_distribution_major_version }}-{{ ansible_machine }}.yml"

# 2024-05-13: Oracle Linux Server release 8.9 does not support any ansible_* variable
- name: Include ansible_system-ansible_distribution.yml / ansible_system.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_distribution }}.yml" # Linux-Debian.yml
      - "{{ ansible_system }}.yml" # FreeBSD.yml

- name: Copy low level discovery (lld) helper scripts
  ansible.builtin.template:
    src: "{{ item }}"
    # Same for Linux and FreeBSD
    dest: /opt/bin/
    mode: "0644"
  loop:
    - zabbix_lld.py

- name: Copy low level discovery (lld) scripts (1/2)
  ansible.builtin.copy:
    src: "{{ item }}"
    # Same for Linux and FreeBSD
    dest: /opt/bin/
    mode: "0755"
  loop:
    - zabbix-lld-from-file

- name: Copy low level discovery (lld) scripts
  ansible.builtin.template:
    src: "{{ item }}"
    # Same for Linux and FreeBSD
    dest: /opt/bin/
    mode: "0755"
  loop:
    - zabbix-lld-services
    - zabbix-lld-tcp-services

# Every OS specific playbook must set_fact zabbix_agent_conf_dir
- name: Copy local-userparameter_*
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_conf_dir }}"
    mode: "644"
  with_items:
    - local-userparameter_ntp_client.conf
    - local-userparameter_tcp_services.conf
    - local-userparameter_local-vfs-dir-count.conf
    - local-userparameter_local-vfs-file-owner.conf
  notify: Restart zabbix-agent

# e.g. files/etc/zabbix_agentd.conf.d/local-my.host.conf
- name: Copy local-{{ inventory_hostname }}.conf # noqa name
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_conf_dir }}/local.conf"
    mode: "644"
  with_first_found:
    - files:
        - etc/zabbix_agentd.conf.d/local-{{ inventory_hostname }}.conf
      skip: true
  notify: Restart zabbix-agent

- name: Remove deprecated files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ zabbix_agent_conf_dir }}/local-userparameter_systemd-timesyncd-timedatectl.conf"
    - /usr/local/bin/zabbix-lld-services
    - /usr/local/bin/zabbix-lld-tcp-services
    - /usr/local/bin/zabbix_lld.py
  notify: Restart zabbix-agent
