---

# We use ansible_lsb.id instead of ansible_distribution as this adds support for 
# UCS (Univention Corporate Server) which reports ansible_distribution=Debian and
# ansible_lsb.id=Univention

- name: Include ansible_system-ansible_lsb.id_ansible_lsb.major_release.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: ansible_lsb is defined and ansible_lsb.id is defined and tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_lsb.id|default('') }}_{{ ansible_lsb.major_release|default('') }}.yml"

- name: Include ansible_system-ansible_distribution_ansible_distribution_major_version-ansible_machine.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  when: (ansible_lsb is not defined or ansible_lsb.id is not defined) and tasks_file != ""
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_distribution }}_{{ ansible_distribution_major_version }}-{{ ansible_machine }}.yml"

- name: Include ansible_system-ansible_distribution.yml / ansible_system.yml
  ansible.builtin.include_tasks: "{{ tasks_file }}"
  vars:
    tasks_file: "{{ lookup('ansible.builtin.first_found', files, errors='ignore') }}"
    files:
      - "{{ ansible_system }}-{{ ansible_distribution }}.yml"  # Linux-Debian.yml
      - "{{ ansible_system }}.yml"  # FreeBSD.yml

# Every OS specific playbook must set_fact zabbix_agent_conf_dir
- name: Copy local-userparameter_*
  copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_conf_dir }}"
  with_items:
    - local-userparameter_local-vfs-dir-count.conf
    - local-userparameter_local-vfs-file-owner.conf
    - local-userparameter_local-web-page-get.conf
  notify: Restart zabbix-agent

# e.g. files/etc/zabbix_agentd.conf.d/local-my.host.conf
- name: Copy local-{{ inventory_hostname }}.conf
  copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_conf_dir }}/local.conf"
  with_first_found:
    - files:
      - "etc/zabbix_agentd.conf.d/local-{{ inventory_hostname }}.conf"
      skip: yes
  notify: Restart zabbix-agent

- name: Remove deprecated local-userparameter_*
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf_dir }}/local-userparameter_systemd-timesyncd-timedatectl.conf"
    state: absent
  notify: Restart zabbix-agent

