---

# Also see mit.zabbix-agent.common/vars/OpenBSD.yml

- name: Install zabbix-agent
  ansible.builtin.package:
    name: zabbix-agent

- name: Create {{ zabbix_agent_conf_dir }}
  file:
    path: "{{ zabbix_agent_conf_dir }}"
    state: directory

- name: Enable include of {{ zabbix_agent_conf_dir }}/*.conf
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Include=\/etc\/zabbix\/zabbix_agentd\.conf\.d\/\*\.conf'
    line: 'Include={{ zabbix_agent_conf_dir }}/*.conf'

- name: Configure zabbix-agent ({{ zabbix_agent_conf }})
  template:
    src: "{{ zabbix_agent_conf }}"
    # We use the same name for all which makes it easier if we change the
    # template for some hosts (myconf1.conf -> myconf2.conf)
    dest: "{{ zabbix_agent_conf_dir }}/local-zabbix_agentd.conf"
    mode: 0644
  notify: "Restart zabbix-agent"

#- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (1/2)
#  shell: openssl rand -hex 32 > {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk
#  args:
#    creates: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
#  notify: Restart zabbix-agent
#
#- name: Create {{ zabbix_agent_conf_dir }}/zabbix_agentd.psk (2/2)
#  file:
#    path: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.psk"
#    owner: root
#    group: zabbix
#    mode: 0640

#- name: Copy local-userparameter_*
#  copy:
#    src: "FreeBSD/{{ item }}"
#    dest: "{{ zabbix_agent_conf_dir }}"
#  with_items:
#    - local-userparameter_service.conf
#    - local-userparameter_system-sw-packages-version.conf
#  notify: Restart zabbix-agent

#- name: Gather the package facts
#  ansible.builtin.package_facts:
#    manager: auto
#
#- name: Copy logcheck rules
#  copy:
#    src: logcheck-zabbix-agent
#    dest: /etc/logcheck/ignore.d.server/mit-defaults-zabbix-agent
#  when: "'logcheck' in ansible_facts.packages"

# logrotate
# /usr/local/etc/newsyslog.conf.d should have been created by role mit.basic
#- name: Copy /usr/local/etc/newsyslog.conf.d/zabbix_agentd.conf
#  copy:
#    src: newsyslog-zabbix_agentd.conf
#    dest: /usr/local/etc/newsyslog.conf.d/zabbix_agentd.conf

# Ensure to use name.service and not only name
- name: Start the zabbix-agent service
  service:
    name: zabbix_agentd
    state: started
    enabled: yes

