---

- set_fact:
    zabbix_major_version: "{{ zabbix_agent_version | regex_replace('^([0-9]+\\.[0-9]+)(.*)$', '\\1') }}"
    zabbix_agent_package: "zabbix-agent_{{ zabbix_agent_version }}-1+{{ ansible_distribution_release }}_amd64.deb"
    zabbix_sender_package: "zabbix-sender_{{ zabbix_agent_version }}-1+{{ ansible_distribution_release }}_amd64.deb"

- name: Download zabbix-agent v{{ zabbix_agent_version }} from zabbix.org
  # Providing the name of the destination file will skip the download if the file exists
  get_url:
    url: https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/debian/pool/main/z/zabbix/{{ zabbix_agent_package }}
    dest: /var/cache/apt/archives/{{ zabbix_agent_package }}

- name: Download zabbix-sender v{{ zabbix_agent_version }} from zabbix.org
  # Providing the name of the destination file will skip the download if the file exists
  get_url:
    url: https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/debian/pool/main/z/zabbix/{{ zabbix_sender_package }}
    dest: /var/cache/apt/archives/{{ zabbix_sender_package }}

- name: Installing zabbix-agent v{{ zabbix_agent_version }}
  apt:
    deb: /var/cache/apt/archives/{{ zabbix_agent_package }}

- name: Installing zabbix-sender v{{ zabbix_agent_version }}
  apt:
    deb: /var/cache/apt/archives/{{ zabbix_sender_package }}

# Debian default
- name: Set include to zabbix_agentd.conf.d
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Include='
    line: Include=/etc/zabbix/zabbix_agentd.conf.d/*.conf
  notify: Restart zabbix-agent

# Debian default
- name: Set LogFile to /var/log/zabbix-agent/zabbix_agentd.log
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^LogFile='
    line: LogFile=/var/log/zabbix-agent/zabbix_agentd.log
  notify: Restart zabbix-agent

- name: Remove deprecated zabbix_agentd.d
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agentd.d
    state: absent 

