#!/usr/bin/env python3
#
# Distributed via ansible - mit.zabbix-agent.package
#
# Reports all configured services.
#
# /etc/zabbix/mit-zabbix-lld-tcp-services.conf:
#
# - service
# - display name
# 
# v2024-07-16 by markus.meissner@meissner.IT

import csv
import json
import glob
import os

data = list()


# Custom
conffile = '{{ etc_prefix }}/etc/zabbix/mit-zabbix-lld-services.conf'
if os.path.exists(conffile):
    with open(conffile) as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            if len(row)>0 and not row[0].startswith('#'):
                data.append({
                        "{{ '{#SERVICE}' }}": row[0],
                        "{{ '{#DISPLAY_NAME}' }}": row[1] if len(row)>1 else row[0]})

# Output all
print(json.dumps({"data": data}, indent=4))

