#!/usr/bin/env python3
#
# Distributed via ansible - mit.zabbix-agent.package
#
# Reports all configured services.
#
# /etc/zabbix/mit-zabbix-lld-tcp-services.conf:
#
# - PORT
# - DISPLAY_NAME (set to 'BY_SERVICE_DESCRIPTION' for getting the name via service / systemctl)
# - TAG
# 
# v2024-07-16 by markus.meissner@meissner.IT

import csv
import json
import glob
import os
import subprocess
import zabbix_lld

data = list()


# Custom
conffile = '/etc/zabbix/mit-zabbix-lld-tcp-services.conf'
if os.path.exists(conffile):
    with open(conffile) as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            if len(row)>0 and not row[0].startswith('#'):
                data.append({
                        "{{ '{#PORT}' }}": row[0],
                        "{{ '{#DISPLAY_NAME}' }}": zabbix_lld.get_service_name(row[1]),
                        "{{ '{#TAG}' }}": row[2] if len(row)>2 else ""})

# Output all
print(json.dumps({"data": data}, indent=4))

